obj-$(CONFIG_IPA) += ipa.o

ipa-y := ipa_main.o ipa_debugfs.o ipa_dp.o ipa_client.o \
		ipa_utils.o ipa_interrupts.o ipa_uc.o
ipa-y += gsi.o

obj-$(CONFIG_IPA) += rmnet_ipa.o ipa_qmi_service_v01.o ipa_qmi_service.o

obj-$(CONFIG_IPA) += ipahal/
