obj-$(CONFIG_RMNET_IPA_LITE) += rmnet_ipa.o ipa_qmi_service_v01.o ipa_qmi_service.o

obj-$(CONFIG_IPA_LITE) += ipat.o
ipat-y := ipa.o ipa_debugfs.o ipa_dp.o ipa_client.o \
	ipa_utils.o ipa_interrupts.o \
	ipa_uc.o

obj-$(CONFIG_IPA_LITE) += ipahal/
obj-$(CONFIG_IPA_LITE) += gsi/
